# handlers/main.yml
---
- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Reload prometheus config and restart
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true # Ensures systemd reloads unit file if changed