---
# tasks file for redis_install

- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Update cache if older than 1 hour

- name: Install Redis server package
  ansible.builtin.apt:
    name: redis-server
    state: present
  become: true
  notify: "restart redis service" # Restart if Redis server is newly installed or updated

- name: Configure Redis bind address
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind ' # Regex to match the 'bind' line
    line: "bind {{ redis_bind_address }}" # Set the bind address using the variable
    owner: redis
    group: redis
    mode: '0644'
    state: present
    backup: yes # Create a backup of the original file before modifying
  become: true
  notify: "restart redis service" # Restart Redis if the bind address changes

- name: Configure Redis port (if different from default)
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^port ' # Regex to match the 'port' line
    line: "port {{ redis_port }}" # Set the port using the variable
    owner: redis
    group: redis
    mode: '0644'
    state: present
    backup: yes
  when: redis_port != 6379 # Only run if the port is explicitly changed from default
  notify: "restart redis service"