- name: Establish Bastion tunnel
  hosts: localhost
  vars_files:
    - /var/lib/jenkins/vars.yml
  vars:
    resource_group: "internship-rg"
    vm_name: "{{app_vm_name}}"
    local_port: 50023
  roles:
    - bastion
- name: Run container from specified image and parametres
  hosts: appvm
  vars:
    container_name: "my_blood_front"
    image: "kaashntr/blood_is_fuel:latest"
    ports:
      - "3000:3000"
    env_vars: {"BACKEND_URL":"{{lookup('env','BACKEND_URL')}}"}
    restart_policy: "always"
    volumes: []
    network_mode: "bridge"
    pull_image: "no"
    container_extra_args: []
  roles:
    - run_container