- name: Establish Bastion tunnel
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    resource_group: "internship-rg"
    vm_name: "{{backend_vm_name}}"
    local_port: 50024
  roles:
    - bastion
- name: Install docker on vm
  hosts: backendvm 
  become: true
  roles:
    - docker_install