- name: Deploy and configure application on target VM via Bastion tunnel
  hosts: localhost
  vars:
    resource_group: "inernship_rg"
  roles:
    - bastion

- name: Restore DB from dump file
  hosts: backendvm
  gather_facts: true
  vars_files:
    - vars.yml
  vars:
    

  roles:
    - restore_from_dump

