- name: Establish Bastion tunnel
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    resource_group: "internship-rg"
    vm_name: "{{redis_vm_name}}"
    local_port: 50025
  roles:
    - bastion

- name: Install and config redis
  hosts: redisvm
  gather_facts: true
  vars:
    redis_bind_address: "0.0.0.0"
  become: true
  roles:
    - redis_install
