# defaults/main.yml
node_exporter_version: "1.8.1" # Check for the latest stable version on GitHub releases
node_exporter_arch: "amd64"    # Change if you're targeting ARM (e.g., "arm64")
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_listen_address: "0.0.0.0:9100"
node_exporter_enabled_collectors: [] # List of collectors to explicitly enable, if not default
# Example: node_exporter_enabled_collectors: ["textfile"]
node_exporter_disabled_collectors: [] # List of collectors to disable
# Example: node_exporter_disabled_collectors: ["wifi", "netstat"]
node_exporter_extra_args: "" # Any other command-line arguments

# URL for downloading Node Exporter
# You can customize this if you host your own binaries
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"